---
- name: "Install dependencies required for python packages"
  become: yes
  apt:
    name: ["python3-pip"]

- name: install pre-requisites
  pip:
    name:
      - pyyaml
      - kubernetes

- name: Get ansible homedir
  shell: echo ~
  register: ansible_home
  ignore_errors: true
  become: false

- name: Set kubeconfig path
  ansible.builtin.set_fact: kubeconfig="{{ ansible_home.stdout_lines[0] }}/.kube/config"